### ISSUE TITLE
Address doesn't support default

### ISSUE THREAD

**Issue by ex-tag** [dradtke/braintree-rs#1]
Trying to use:

```
billing: Some(Address{
  street_address: Some(String::from(street_address)),
  locality: Some(String::from(locality)),
  region: Some(String::from(region)),
  postal_code: Some(String::from(postal_code)),
   ..Default::default()
})
```
And getting the following error:

> ..Default::default()
    |           ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `braintree::Address`

Think that your derive attribute on the Address struct is missing `Default`. Is this a design choice, or should this be `#[derive(Debug, Default)]`?

**Comment by dradtke** [comment]
Fixed in https://github.com/dradtke/braintree-rs/commit/2247c8b8bb0b2fa531e0822fa4fde62b783475c4.
